/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input [111:0] user_input_all,
    input [111:0] bull_cow_input,
    output reg outled1,
    output reg outled2,
    output reg outled3,
    output reg outled4,
    output reg outled5,
    output reg outled6,
    output reg outled7,
    output reg outled8
  );
  
  
  
  reg rst;
  
  reg [63:0] userled;
  
  reg [63:0] bullsandcowled;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_ledout1_led;
  reg [32-1:0] M_ledout1_color;
  reg [1-1:0] M_ledout1_update;
  ws2812b_2 ledout1 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout1_color),
    .update(M_ledout1_update),
    .led(M_ledout1_led)
  );
  wire [1-1:0] M_ledout2_led;
  reg [32-1:0] M_ledout2_color;
  reg [1-1:0] M_ledout2_update;
  ws2812b_2 ledout2 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout2_color),
    .update(M_ledout2_update),
    .led(M_ledout2_led)
  );
  wire [1-1:0] M_ledout3_led;
  reg [32-1:0] M_ledout3_color;
  reg [1-1:0] M_ledout3_update;
  ws2812b_2 ledout3 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout3_color),
    .update(M_ledout3_update),
    .led(M_ledout3_led)
  );
  wire [1-1:0] M_ledout4_led;
  reg [32-1:0] M_ledout4_color;
  reg [1-1:0] M_ledout4_update;
  ws2812b_2 ledout4 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout4_color),
    .update(M_ledout4_update),
    .led(M_ledout4_led)
  );
  wire [1-1:0] M_ledout5_led;
  reg [32-1:0] M_ledout5_color;
  reg [1-1:0] M_ledout5_update;
  ws2812b_2 ledout5 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout5_color),
    .update(M_ledout5_update),
    .led(M_ledout5_led)
  );
  wire [1-1:0] M_ledout6_led;
  reg [32-1:0] M_ledout6_color;
  reg [1-1:0] M_ledout6_update;
  ws2812b_2 ledout6 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout6_color),
    .update(M_ledout6_update),
    .led(M_ledout6_led)
  );
  wire [1-1:0] M_ledout7_led;
  reg [32-1:0] M_ledout7_color;
  reg [1-1:0] M_ledout7_update;
  ws2812b_2 ledout7 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout7_color),
    .update(M_ledout7_update),
    .led(M_ledout7_led)
  );
  wire [1-1:0] M_ledout8_led;
  reg [32-1:0] M_ledout8_color;
  reg [1-1:0] M_ledout8_update;
  ws2812b_2 ledout8 (
    .clk(clk),
    .rst(rst),
    .color(M_ledout8_color),
    .update(M_ledout8_update),
    .led(M_ledout8_led)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    userled = 423'h4110d6132dcb1be0a582d0a3cbedf122d558d1cfe7a19637b58306c3fe745377bb48c952a89e5829dd3f0e3bbe1830f53debfba839;
    bullsandcowled = 423'h4110d6132dcb1be0a582d0a3cbedf122d558d1cfe7a19637b58306c3fe745377bb48c952a89e5829dd3f0e3bbe1830f53debfba839;
    M_ledout1_update = 1'h1;
    M_ledout1_color = {bullsandcowled[0+3-:4], bullsandcowled[4+3-:4], bullsandcowled[8+3-:4], bullsandcowled[12+3-:4], userled[0+3-:4], userled[4+3-:4], userled[8+3-:4], userled[12+3-:4]};
    outled1 = M_ledout1_led;
    M_ledout2_update = 1'h1;
    M_ledout2_color = 32'hdd709359;
    outled2 = M_ledout2_led;
    M_ledout3_update = 1'h1;
    M_ledout3_color = 32'hdd709359;
    outled3 = M_ledout3_led;
    M_ledout3_update = 1'h1;
    M_ledout3_color = 32'hdd709359;
    outled3 = M_ledout3_led;
    M_ledout4_update = 1'h1;
    M_ledout4_color = 32'hdd709359;
    outled4 = M_ledout4_led;
    M_ledout5_update = 1'h1;
    M_ledout5_color = 32'hdd709359;
    outled5 = M_ledout5_led;
    M_ledout6_update = 1'h1;
    M_ledout6_color = 32'hdd709359;
    outled6 = M_ledout6_led;
    M_ledout7_update = 1'h1;
    M_ledout7_color = 32'hdd709359;
    outled7 = M_ledout7_led;
    M_ledout8_update = 1'h1;
    M_ledout8_color = 32'h00009359;
    outled8 = M_ledout8_led;
  end
endmodule
